version: "3"
services:
  server:
    build:
      context: server
    container_name: server
    working_dir: /app/server
    ports:
      - 3000:3000
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    command: yarn run start:dev
  client:
    build:
      context: client
    container_name: client
    working_dir: /app/client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    command: yarn run dev
    depends_on:
      - server
